version: '3.8'

services:
  web:
    container_name: spring
    image: cswcsm02/refit-spring
    expose:
      - 8080
    ports:
      - 8080:8080

  nginx:
    container_name: nginx
    image: cswcsm02/refit-nginx
    ports:
      - 80:80
    depends_on:
      - web