spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  output:
    ansi:
      enabled: ALWAYS

  datasource:
    url: jdbc:mysql://localhost:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver



  jpa:
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
        default_batch_fetch_size: 100

  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true

  security:
    oauth2:
      resourceserver:
        jwt:
          jws-algorithms: RS512

  redis:
    host: localhost
    port: 6379


cloud:
  aws:
    stack:
      auto: false
    region:
      static: ap-northeast-2
    s3:
      bucket: refit-bucket
    credentials:
      access-key: ${S3_KEY}
      secret-key: Rx4PxP50wf4P9JHj1MNDAqZw8SZ8+8Z8zQhdZHm4


logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error

token:
  issuer: http://localhost:8080
